name: Node.js CI

on:
  push:
    branches: 
      - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
          - 14.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install hexo
      run: npm -g install hexo
    - name: npm audit fix
      run: npm audit fix
    - name: hexo generate
      run: hexo clean && hexo g
    - name: git push public
      working-directory: ./public
    - run: pwd 
    - run: ls
    - run: git init
    - run: git config user.name "Young Bean"
    - run: git config user.email "xxl115@163.com"
    - run: git add .
    - run: git commit -a -m "Auto update docs by Travis CI."
    - run: git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
    env:
      GH_REF: 'github.com/xxl115/xxl115.github.io.git'