name: Node.js CI

on:
  push:
    branches: 
      - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
          - 14.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install hexo
      run: |
        npm -g install hexo
        npm audit fix
    - name: hexo generate
      run: |
        hexo clean 
        hexo generate
    - name: Commit files
      working-directory: ./public
      run: |
        git init
        git config user.name "Young Bean" 
        git config user.email "xxl115@163.com"
        git add .
        git commit -a -m "Auto update docs by Travis CI."
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true
        directory: ./public