name: Node.js CI

on:
  push:
    branches: 
      - hexo
  # pull_request:
    # branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
          - 14.x
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm -g install hexo
    - run: npm audit fix
    - run: hexo clean
    - run: hexo g
    - run: pwd
    - run: ls
    - run: cd public
    - run: pwd
    - run: ls
    - run: cd ./public
    - run: ls
    # - run: git init
    # - run: git config user.name "Young Bean"
    # - run: git config user.email "xxl115@163.com"
    # - run: git add .
    # - run: git commit -a -m "Auto update docs by Travis CI."
    # - run: git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
    env:
      GH_REF: 'github.com/blinkfox/blinkfox.github.io.git'
# env:
#  global:
#    - GH_REF: github.com/blinkfox/blinkfox.github.io.git